---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: benjibackupschedules.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - schedule
                - persistentVolumeClaimSelector
              properties:
                schedule:
                  type: string
                persistentVolumeClaimSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: string
  names:
    kind: BenjiBackupSchedule
    plural: benjibackupschedules
    singular: benjibackupschedule
    shortNames:
      - benjibss
      - benjibs
