---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbenjibackupschedules.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Cluster
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - schedule
                - persistentVolumeClaimSelector
                - namespaceSelector
              properties:
                schedule:
                  type: string
                persistentVolumeClaimSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: string
                namespaceSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: ClusterBenjiBackupSchedule
    plural: clusterbenjibackupschedules
    singular: clusterbenjibackupschedule
    shortNames:
      - cbenjibss
      - cbenjibs
