---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: benjiretentionschedules.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - schedule
                - retentionRule
              properties:
                schedule:
                  type: string
                retentionRule:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: BenjiRetentionSchedule
    plural: benjiretentionschedules
    singular: benjiretentionschedule
    shortNames:
      - benjirts
      - benjirt
