apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: benjirestores.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - versionName
                - persistentVolumeClaimName
              properties:
                versionName:
                  type: string
                persistentVolumeClaim:
                  type: string
                overwrite:
                  type: boolean
                  default: false
                storageClassName:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: BenjiRestore
    plural: benjirestores
    singular: benjirestore
    shortNames:
      - benjirs
      - benjir
