---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ tuple . "" | include "benji.fullname" }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - namespaces
    - persistentvolumes
    - pods
  verbs:
    - list
    - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
    - "benji-backup.me"
  resources:
    - benjirestores
    - benjiversions
    - benjibackups
  verbs:
    - create
    - update
    - get
    - list
    - patch
- apiGroups:
    - benji-backup.me
  resources:
    - benjiversions
  verbs:
    - delete
{{- if .Values.fsfreeze.enabled }}
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  # Also needs GET where kubectl doesn't, see https://github.com/kubernetes-client/python/issues/690#issuecomment-459010364
  - get
{{- end}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ tuple . "operator" | include "benji.fullname" }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - "zalando.org"
    resources:
      - clusterkopfpeerings
      - kopfpeerings
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "benji-backup.me"
    resources:
      - benjirestores
      - benjibackups
      - benjibackupschedules
      - clusterbenjibackupschedules
      - benjiretentionschedules
      - clusterbenjiretentionschedules
      - benjiversions
      - benjioperatorconfigs
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - delete
